// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VFM.Models.Help;

#nullable disable

namespace VFM.Migrations
{
    [DbContext(typeof(LiteDbContext))]
    partial class LiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.30");

            modelBuilder.Entity("VFM.Models.Users.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("createF")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("deleteF")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("downloadF")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("isAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("updateNameF")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("uploadF")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
